### ISSUE TITLE
XP Orbs @ worldspawn

### ISSUE THREAD

**Issue by Freebi85** [Furgl/AutoPickup#10]
Hello =)
Seems that when a mob dies to the hands of fake players like evilcraft spikes, Draconic Evolution Mob Grinder or even to the hands of another mob (skelies fights) XP Orbs are spawned at the world spawn.
Especially on servers this leads to massive laags after a while.
Can you help us with this problem?

**Comment by Furgl** [comment]
Try v2.5.1, it should fix that issue.
[AutoPickup-1.12-2.5.1.jar.zip](https://github.com/Furgl/AutoPickup/files/2990403/AutoPickup-1.12-2.5.1.jar.zip)

**Comment by Freebi85** [comment]
Thank you very much! I will test it tonight and let you know then.

**Comment by Freebi85** [comment]
So I tested it yesterday. Seems to be working correctly now. Many thanks for the fix =)
