### ISSUE TITLE
AutoAdd cannot be disabled

### ISSUE THREAD

**Issue by C0rn3j** [Furgl/AutoPickup#3]
http://i.imgur.com/HS3FZHu.png

Forge 2092

AutoPickup-1.10.2-2.2.jar

Also I'd appreciate if it was off by default

**Comment by Furgl** [comment]
https://gyazo.com/c8318d3c746549629c820a2859cb87c6

I tested on single player and a server and was unable to replicate this bug. Can you provide more information about it: was this in single player or multiplayer and were there any errors in the console?

**Comment by C0rn3j** [comment]
This was tested on an MP server running in OFFLINE MODE. Might be related to that, I'll try retesting sometime soon.

By the way, if you're on Windows I suggest you use(or at least check out) ShareX instead of Gyazo. Open source solution and all that.

**Comment by C0rn3j** [comment]
Tried messing with it for a few minutes and it worked fine, not sure what is triggering it.

**Comment by Furgl** [comment]
If this happens again and you can replicate it, please open another issue and I'll take a look at it. Thanks!
