### ISSUE TITLE
1.10.2 AutoAdd preference resetting on server restart

### ISSUE THREAD

**Issue by GodsVictory** [Furgl/AutoPickup#4]
I'm forced to disable autoadd manually after a server restart

forge: 1.10.2-12.18.2.2099
autopickup: 1.10.2-2.2

**Comment by Furgl** [comment]
This has been fixed in v2.3, thank you for telling me about it!
[AutoPickup-1.10.2-2.3.jar.zip](https://github.com/Furgl/AutoPickup/files/582506/AutoPickup-1.10.2-2.3.jar.zip)
